# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 00:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cod', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(blank=True, max_length=155, verbose_name='Endereço')),
                ('person_type', models.CharField(default='Pessoa Física', max_length=55)),
                ('document', models.IntegerField(verbose_name='Núm. Documento')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('cod', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Nome')),
                ('in_stock', models.IntegerField()),
                ('price_sale', models.DecimalField(decimal_places=6, max_digits=12, verbose_name='Preço de venda')),
                ('price_cost', models.DecimalField(decimal_places=6, max_digits=12, verbose_name='Preço de custo')),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('cod', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(blank=True, max_length=155, verbose_name='Endereço')),
                ('person_type', models.CharField(default='Pessoa Física', max_length=55)),
                ('document', models.IntegerField(verbose_name='Núm. Documento')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('cod', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateField()),
                ('date_closed', models.DateField()),
                ('status', models.CharField(default='Em aberto', max_length=55, verbose_name='Status')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edpell_notas.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Sale_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edpell_notas.Product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edpell_notas.Sale')),
            ],
        ),
        migrations.CreateModel(
            name='Sale_Unit',
            fields=[
                ('cod', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=55)),
                ('amount', models.IntegerField()),
                ('price_mult', models.DecimalField(decimal_places=6, default=1, max_digits=8, verbose_name='Incremento de preço')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edpell_notas.Product')),
            ],
        ),
        migrations.AddField(
            model_name='sale',
            name='products',
            field=models.ManyToManyField(through='edpell_notas.Sale_Item', to='edpell_notas.Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='provider',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='edpell_notas.Provider'),
        ),
    ]
